### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iBeech**
Added information RE multiple subnet support

### CODE REVIEW

**Comment by iBeech** [comment]
I’m not familiar with your build / release pipeline. When do you expect this to be released?

Thanks,
Tom

**Comment by ilteoood** [comment]
It will be released after some tests.
At most on Monday morning.

**Comment by iBeech** [comment]
Excellent. Thank you. How could I test this out myself?

Thanks

**Comment by iBeech** [comment]
Any idea why the build is failing?

**Comment by ilteoood** [comment]
Randomly it fails. Now is ok.

**Comment by iBeech** [comment]
Great! Did you manage to get any testing done?

**Pull request merged**
